### ISSUE TITLE
The extension does not work for recent versions of Gnome

### ISSUE THREAD

**Issue by ikuraj** [brunonova/nautilus-hide#1]
On gnome-shell 3.20.4, the icons still appear; i.e. hiding/unhiding icons does not have any effects.

**Comment by brunonova** [comment]
I'll take a look at this when I have the time.
[nautilus-admin](https://github.com/brunonova/nautilus-admin) is also [having problems](https://github.com/brunonova/nautilus-admin/issues/19) with newer GNOME versions.

**Comment by brunonova** [comment]
Sorry for the delay.

I launched an LXD container with Debian Testing (Nautilus 3.22.0) to test this bug, but I couldn't reproduce it.
I have also been trying to put Debian Testing in a VirtualBox, but I haven't succeeded yet.

@kaptoxic, could you please test this:
1. Open Nautilus and hide some files using the extension
2. Show the hidden files (`Ctrl`+`H`)
3. See if there is a file named `.hidden`. If there is, see if the files you hid are listed in that file

Thanks!

**Comment by ikuraj** [comment]
Oops, indeed -- it seems I forgot to use "Show the hidden files" (`Ctrl + H`). Seems to be working fine! Awesome, thanks!

**Comment by brunonova** [comment]
Great!

Note, also, that hiding a file using the extension doesn't refresh the window, so the file will stay visible until you refresh (`F5`) or reopen the folder.
