### ISSUE TITLE
Strange delays, PyGIWarning

### ISSUE THREAD

**Issue by ikuraj** [brunonova/nautilus-hide#2]
When this extension is enabled, nautilus takes a lot of time to close properly (e.g. when invoked from the command line and then closed), while reporting this:
```
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
```

**Comment by brunonova** [comment]
I never noticed any additional delays while using the extension.

I just tested this by running `nautilus --no-desktop` and it took roughly the same time to open a close Nautilus.

And that message is just a warning, there's nothing worrying in it.

**Comment by ikuraj** [comment]
Indeed, this issue seems unrelated to the plugin (even though I thought I tested to confirm otherwise). Rather, it seems to be a manifestation of other factors within Gnome.

Indeed, I was thinking that the warning was pretty much harmless.

**Comment by brunonova** [comment]
Great! I'm closing this issue then.

Nautilus does indeed take a lot of time to close.
