### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by Silubr** [brunonova/nautilus-hide#4]
I’ve cobbled together a German translation (going by the French version). I’m a total noob, but so far it works great on my machine (Ubuntu Xenial, Nautilus 1:3.18.4.is.3.14.3-0ubuntu5).

Thanks for your work, by the way!
[de.po.zip](https://github.com/brunonova/nautilus-hide/files/771709/de.po.zip)

**Comment by brunonova** [comment]
Thanks, it's good!
I added it to the project.

You can also use the `msginit` command to create the *.po* file. Something like this:

    msginit -l de -i the_pot_file.pot

This will take care of all those properties at the beginning of the file.
