### ISSUE TITLE
NautilusHide is not initialized

### ISSUE THREAD

**Issue by medicamin** [brunonova/nautilus-hide#9]
Hi there,
I'm getting this error at multiple times in my journalctl log:
`
org.freedesktop.FileManager1[1661]: RuntimeError: object at 0x7fb8ca44d2d0 of type NautilusHide is not initialized`

Gnome 3.26.2
Manjaro 17.1

Everything works, but what is that error? Is there any way to make this fixed?

**Comment by brunonova** [comment]
I have no idea what that error is or why it happens. Maybe someone else with more experience with Nautilus extensions knows.

But, if everything works, it's not too bad. 😄

**Comment by toger5** [comment]
I do get the same error. (using antergos gnome)
> The issue appears to be due to something in get_file_items in the nautilus-gsconnect.py file. Not sure what it's exactly.

from: https://github.com/andyholmes/gnome-shell-extension-gsconnect/issues/146

**Comment by brunonova** [comment]
Thank you @toger5! It seems the fix in the link you provider does fix the error!

I've committed that fix. Could you test it too?

**Comment by toger5** [comment]
Amazing you could react so quickly !! Thank you!
I will test tomorrow hopefully

**Comment by toger5** [comment]
Oh forgot to answer... i did test, and it works fine now!

**Comment by TomaArihara** [comment]
RuntimeError: object at 0x7f3920772870 of type FolderColorMenu is not initialized

In my case, this will come out.
Where should I repair?

**Comment by brunonova** [comment]
@TomaArihara that looks like another extension. Nautilus Hide doesn't contain anything named FolderColorMenu.
